"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WETH__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var WETH__factory_1 = require("./WETH__factory");
Object.defineProperty(exports, "WETH__factory", { enumerable: true, get: function () { return WETH__factory_1.WETH__factory; } });
