"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GhoulsScript__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var GhoulsScript__factory_1 = require("./GhoulsScript__factory");
Object.defineProperty(exports, "GhoulsScript__factory", { enumerable: true, get: function () { return GhoulsScript__factory_1.GhoulsScript__factory; } });
