"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PaymentSplitter__factory = exports.Pausable__factory = exports.Ownable__factory = exports.IERC721A__factory = exports.IERC2981__factory = exports.IERC20__factory = exports.IERC165__factory = exports.GhoulsShares__factory = exports.GhoulsRoyalties__factory = exports.Ghouls__factory = exports.ERC721ABase__factory = exports.ERC2981__factory = exports.ERC165__factory = exports.DevilsCut__factory = exports.wethSol = exports.draftIerc20PermitSol = exports.erc721ASol = exports.devilsCutSSol = exports.counterSSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.counterSSol = __importStar(require("./Counter.s.sol"));
exports.devilsCutSSol = __importStar(require("./DevilsCut.s.sol"));
exports.erc721ASol = __importStar(require("./ERC721A.sol"));
exports.draftIerc20PermitSol = __importStar(require("./draft-IERC20Permit.sol"));
exports.wethSol = __importStar(require("./weth.sol"));
var DevilsCut__factory_1 = require("./DevilsCut__factory");
Object.defineProperty(exports, "DevilsCut__factory", { enumerable: true, get: function () { return DevilsCut__factory_1.DevilsCut__factory; } });
var ERC165__factory_1 = require("./ERC165__factory");
Object.defineProperty(exports, "ERC165__factory", { enumerable: true, get: function () { return ERC165__factory_1.ERC165__factory; } });
var ERC2981__factory_1 = require("./ERC2981__factory");
Object.defineProperty(exports, "ERC2981__factory", { enumerable: true, get: function () { return ERC2981__factory_1.ERC2981__factory; } });
var ERC721ABase__factory_1 = require("./ERC721ABase__factory");
Object.defineProperty(exports, "ERC721ABase__factory", { enumerable: true, get: function () { return ERC721ABase__factory_1.ERC721ABase__factory; } });
var Ghouls__factory_1 = require("./Ghouls__factory");
Object.defineProperty(exports, "Ghouls__factory", { enumerable: true, get: function () { return Ghouls__factory_1.Ghouls__factory; } });
var GhoulsRoyalties__factory_1 = require("./GhoulsRoyalties__factory");
Object.defineProperty(exports, "GhoulsRoyalties__factory", { enumerable: true, get: function () { return GhoulsRoyalties__factory_1.GhoulsRoyalties__factory; } });
var GhoulsShares__factory_1 = require("./GhoulsShares__factory");
Object.defineProperty(exports, "GhoulsShares__factory", { enumerable: true, get: function () { return GhoulsShares__factory_1.GhoulsShares__factory; } });
var IERC165__factory_1 = require("./IERC165__factory");
Object.defineProperty(exports, "IERC165__factory", { enumerable: true, get: function () { return IERC165__factory_1.IERC165__factory; } });
var IERC20__factory_1 = require("./IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
var IERC2981__factory_1 = require("./IERC2981__factory");
Object.defineProperty(exports, "IERC2981__factory", { enumerable: true, get: function () { return IERC2981__factory_1.IERC2981__factory; } });
var IERC721A__factory_1 = require("./IERC721A__factory");
Object.defineProperty(exports, "IERC721A__factory", { enumerable: true, get: function () { return IERC721A__factory_1.IERC721A__factory; } });
var Ownable__factory_1 = require("./Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var Pausable__factory_1 = require("./Pausable__factory");
Object.defineProperty(exports, "Pausable__factory", { enumerable: true, get: function () { return Pausable__factory_1.Pausable__factory; } });
var PaymentSplitter__factory_1 = require("./PaymentSplitter__factory");
Object.defineProperty(exports, "PaymentSplitter__factory", { enumerable: true, get: function () { return PaymentSplitter__factory_1.PaymentSplitter__factory; } });
