"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DevilsCutScript__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DevilsCutScript__factory_1 = require("./DevilsCutScript__factory");
Object.defineProperty(exports, "DevilsCutScript__factory", { enumerable: true, get: function () { return DevilsCutScript__factory_1.DevilsCutScript__factory; } });
